title: モンスタリウム
description: 属性世界のモンスター記録集
url: "https://archivista-creats.github.io"
baseurl: "/monsterdex"

remote_theme: mmistakes/minimal-mistakes
markdown: kramdown
highlighter: rouge

# プラグイン設定
plugins:
  - jekyll-include-cache
  - jekyll-archives

# コレクション設定
collections:
  monsters:
    output: true
    permalink: /monster/:path/

# デフォルト設定
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
  - scope:
      path: ""
      type: monsters
    values:
      layout: single
      permalink: /monster/:title/

# ナビゲーション設定（必要なら）
# nav: ...

# jekyll-archives の設定（タグページを有効化）
jekyll-archives:
  enabled:
    - tags
  layouts:
    tag: archive-taxonomy
  permalinks:
    tag: /tags/:name/

# ソーシャルなど必要に応じて
# social: ...
